sudo: required

language: python

python:
    - "2.7"

services:
    - docker

install:
    - make docker-cpu
    
script:
    - docker run --rm ledatelescope/bifrost /bin/sh -c "cd /bifrost/test && sh ./travis.sh"
